### PR TITLE
Add example how to add multiple battery banks without code duplication

### PR DESCRIPTION
**Pull request by martinarva**
There is a main yaml and pack.yaml where all the packs/batteries sensors conf is held. In main yaml you can define the batteries which then use the pack.yaml, so youn dont have to have long duplicated main yaml.

### CODE REVIEW

**Review by syssi — APPROVED** [review]
Super cool! Thanks for your contribution and sorry for the late response.

**Comment by john7doe** [comment]
@martinarva can the packs be read via one pack or does one have to daisy chain the packs?

**Comment by syssi** [comment]
@john7doe Did you see this conversation? https://github.com/syssi/esphome-pace-bms/issues/62

**Comment by john7doe** [comment]
I had not, thanks :-) that answers my question. With RS485 I would have to daisy chain, with RS232 I would be able to read all packs via the master

**Pull request merged**
