### PR TITLE
Make ESP8266 binary sensors identical to ESP32

### PR DESCRIPTION
**Pull request by jingsno**
Fix ESP8266 binary charging sensors, so that they are identical to the ESP32 version

### CODE REVIEW

**Review by syssi — APPROVED** [review]
LGTM! Thanks for your support!

**Comment by jingsno** [comment]
Sigh!

Looks like the two last binary charging sensors are duplicated in the ESP8266 code. Unsure of how that happend. I'm pretty new to git usage, how to fix that? Create a separate pull request?

**Comment by syssi** [comment]
Yes. Please create another pull request. We cannot undo things here.

**Comment by jingsno** [comment]
Ok, will do. The code looks ok in the pull request though. ¯\_(ツ)_/¯

**Pull request merged**
